CREATE DATABASE IF NOT EXISTS app_web
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE app_web;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    senha VARCHAR(200) NOT NULL,
    tipo VARCHAR(20) NOT NULL
);
